// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currency/pair/pair.proto

/*
Package pair is a generated protocol buffer package.

It is generated from these files:
	currency/pair/pair.proto

It has these top-level messages:
	CurrencyPair
*/
package pair

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CurrencyPair struct {
	Delimiter      string `protobuf:"bytes,1,opt,name=Delimiter" json:"Delimiter,omitempty"`
	FirstCurrency  string `protobuf:"bytes,2,opt,name=FirstCurrency" json:"FirstCurrency,omitempty"`
	SecondCurrency string `protobuf:"bytes,3,opt,name=SecondCurrency" json:"SecondCurrency,omitempty"`
}

func (m *CurrencyPair) Reset()                    { *m = CurrencyPair{} }
func (m *CurrencyPair) String() string            { return proto.CompactTextString(m) }
func (*CurrencyPair) ProtoMessage()               {}
func (*CurrencyPair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CurrencyPair) GetDelimiter() string {
	if m != nil {
		return m.Delimiter
	}
	return ""
}

func (m *CurrencyPair) GetFirstCurrency() string {
	if m != nil {
		return m.FirstCurrency
	}
	return ""
}

func (m *CurrencyPair) GetSecondCurrency() string {
	if m != nil {
		return m.SecondCurrency
	}
	return ""
}

func init() {
	proto.RegisterType((*CurrencyPair)(nil), "pair.CurrencyPair")
}

func init() { proto.RegisterFile("currency/pair/pair.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x2e, 0x2d, 0x2a,
	0x4a, 0xcd, 0x4b, 0xae, 0xd4, 0x2f, 0x48, 0xcc, 0x2c, 0x02, 0x13, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x52, 0x15, 0x17, 0x8f, 0x33, 0x54, 0x45, 0x40, 0x62, 0x66, 0x91,
	0x90, 0x0c, 0x17, 0xa7, 0x4b, 0x6a, 0x4e, 0x66, 0x6e, 0x66, 0x49, 0x6a, 0x91, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x42, 0x40, 0x48, 0x85, 0x8b, 0xd7, 0x2d, 0xb3, 0xa8, 0xb8, 0x04, 0xa6,
	0x45, 0x82, 0x09, 0xac, 0x02, 0x55, 0x50, 0x48, 0x8d, 0x8b, 0x2f, 0x38, 0x35, 0x39, 0x3f, 0x2f,
	0x05, 0xae, 0x8c, 0x19, 0xac, 0x0c, 0x4d, 0x34, 0x89, 0x0d, 0xec, 0x10, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa0, 0x5e, 0xcb, 0xc5, 0xa4, 0x00, 0x00, 0x00,
}
