// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/cryptotrader.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc/cryptotrader.proto

It has these top-level messages:
	CurrencyPair
	Value
	ExchangeCurrencies
	EnabledExchangeCurrencies
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CurrencyPair struct {
	Delimiter      string `protobuf:"bytes,1,opt,name=Delimiter" json:"Delimiter,omitempty"`
	FirstCurrency  string `protobuf:"bytes,2,opt,name=FirstCurrency" json:"FirstCurrency,omitempty"`
	SecondCurrency string `protobuf:"bytes,3,opt,name=SecondCurrency" json:"SecondCurrency,omitempty"`
}

func (m *CurrencyPair) Reset()                    { *m = CurrencyPair{} }
func (m *CurrencyPair) String() string            { return proto.CompactTextString(m) }
func (*CurrencyPair) ProtoMessage()               {}
func (*CurrencyPair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CurrencyPair) GetDelimiter() string {
	if m != nil {
		return m.Delimiter
	}
	return ""
}

func (m *CurrencyPair) GetFirstCurrency() string {
	if m != nil {
		return m.FirstCurrency
	}
	return ""
}

func (m *CurrencyPair) GetSecondCurrency() string {
	if m != nil {
		return m.SecondCurrency
	}
	return ""
}

type Value struct {
	Pair         *CurrencyPair `protobuf:"bytes,1,opt,name=Pair" json:"Pair,omitempty"`
	CurrencyPair string        `protobuf:"bytes,2,opt,name=CurrencyPair" json:"CurrencyPair,omitempty"`
	Last         float64       `protobuf:"fixed64,3,opt,name=Last" json:"Last,omitempty"`
	High         float64       `protobuf:"fixed64,4,opt,name=High" json:"High,omitempty"`
	Low          float64       `protobuf:"fixed64,5,opt,name=Low" json:"Low,omitempty"`
	Bid          float64       `protobuf:"fixed64,6,opt,name=Bid" json:"Bid,omitempty"`
	Ask          float64       `protobuf:"fixed64,7,opt,name=Ask" json:"Ask,omitempty"`
	Volume       float64       `protobuf:"fixed64,8,opt,name=Volume" json:"Volume,omitempty"`
	PriceATH     float64       `protobuf:"fixed64,9,opt,name=PriceATH" json:"PriceATH,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Value) GetPair() *CurrencyPair {
	if m != nil {
		return m.Pair
	}
	return nil
}

func (m *Value) GetCurrencyPair() string {
	if m != nil {
		return m.CurrencyPair
	}
	return ""
}

func (m *Value) GetLast() float64 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *Value) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Value) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *Value) GetBid() float64 {
	if m != nil {
		return m.Bid
	}
	return 0
}

func (m *Value) GetAsk() float64 {
	if m != nil {
		return m.Ask
	}
	return 0
}

func (m *Value) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Value) GetPriceATH() float64 {
	if m != nil {
		return m.PriceATH
	}
	return 0
}

type ExchangeCurrencies struct {
	ExchangeName   string   `protobuf:"bytes,1,opt,name=ExchangeName" json:"ExchangeName,omitempty"`
	ExchangeValues []*Value `protobuf:"bytes,2,rep,name=ExchangeValues" json:"ExchangeValues,omitempty"`
}

func (m *ExchangeCurrencies) Reset()                    { *m = ExchangeCurrencies{} }
func (m *ExchangeCurrencies) String() string            { return proto.CompactTextString(m) }
func (*ExchangeCurrencies) ProtoMessage()               {}
func (*ExchangeCurrencies) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExchangeCurrencies) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *ExchangeCurrencies) GetExchangeValues() []*Value {
	if m != nil {
		return m.ExchangeValues
	}
	return nil
}

type EnabledExchangeCurrencies struct {
	ExchangeCurrencies []*ExchangeCurrencies `protobuf:"bytes,1,rep,name=ExchangeCurrencies" json:"ExchangeCurrencies,omitempty"`
}

func (m *EnabledExchangeCurrencies) Reset()                    { *m = EnabledExchangeCurrencies{} }
func (m *EnabledExchangeCurrencies) String() string            { return proto.CompactTextString(m) }
func (*EnabledExchangeCurrencies) ProtoMessage()               {}
func (*EnabledExchangeCurrencies) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EnabledExchangeCurrencies) GetExchangeCurrencies() []*ExchangeCurrencies {
	if m != nil {
		return m.ExchangeCurrencies
	}
	return nil
}

func init() {
	proto.RegisterType((*CurrencyPair)(nil), "grpc.CurrencyPair")
	proto.RegisterType((*Value)(nil), "grpc.Value")
	proto.RegisterType((*ExchangeCurrencies)(nil), "grpc.ExchangeCurrencies")
	proto.RegisterType((*EnabledExchangeCurrencies)(nil), "grpc.EnabledExchangeCurrencies")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for GoCryptoTraderService service

type GoCryptoTraderServiceClient interface {
	GetTickers(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*EnabledExchangeCurrencies, error)
}

type goCryptoTraderServiceClient struct {
	cc *grpc1.ClientConn
}

func NewGoCryptoTraderServiceClient(cc *grpc1.ClientConn) GoCryptoTraderServiceClient {
	return &goCryptoTraderServiceClient{cc}
}

func (c *goCryptoTraderServiceClient) GetTickers(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*EnabledExchangeCurrencies, error) {
	out := new(EnabledExchangeCurrencies)
	err := grpc1.Invoke(ctx, "/grpc.GoCryptoTraderService/GetTickers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoCryptoTraderService service

type GoCryptoTraderServiceServer interface {
	GetTickers(context.Context, *google_protobuf.Empty) (*EnabledExchangeCurrencies, error)
}

func RegisterGoCryptoTraderServiceServer(s *grpc1.Server, srv GoCryptoTraderServiceServer) {
	s.RegisterService(&_GoCryptoTraderService_serviceDesc, srv)
}

func _GoCryptoTraderService_GetTickers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).GetTickers(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GoCryptoTraderService/GetTickers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).GetTickers(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoCryptoTraderService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.GoCryptoTraderService",
	HandlerType: (*GoCryptoTraderServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "GetTickers",
			Handler:    _GoCryptoTraderService_GetTickers_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc/cryptotrader.proto",
}

func init() { proto.RegisterFile("grpc/cryptotrader.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x51, 0x8f, 0xd2, 0x40,
	0x10, 0xc7, 0xed, 0xd1, 0xc3, 0x63, 0xd0, 0x8b, 0xd9, 0xc4, 0x73, 0x45, 0x13, 0x2f, 0x8d, 0xb9,
	0xdc, 0x53, 0x49, 0xb8, 0x4f, 0xc0, 0x21, 0xc2, 0x03, 0x31, 0xa4, 0x10, 0x9e, 0x2d, 0xdb, 0xb1,
	0x6c, 0x68, 0xbb, 0xcd, 0x76, 0xab, 0xe2, 0xf7, 0xf5, 0x7b, 0x98, 0x9d, 0xb6, 0x68, 0x91, 0x7b,
	0x9b, 0xf9, 0xcd, 0xcc, 0xfe, 0xff, 0x3b, 0x19, 0x78, 0x13, 0xeb, 0x5c, 0x0c, 0x85, 0x3e, 0xe4,
	0x46, 0x19, 0x1d, 0x46, 0xa8, 0xfd, 0x5c, 0x2b, 0xa3, 0x98, 0x6b, 0x0b, 0x83, 0x77, 0xb1, 0x52,
	0x71, 0x82, 0x43, 0x62, 0xdb, 0xf2, 0xdb, 0x10, 0xd3, 0xdc, 0x1c, 0xaa, 0x16, 0xef, 0x17, 0xbc,
	0x98, 0x94, 0x5a, 0x63, 0x26, 0x0e, 0xcb, 0x50, 0x6a, 0xf6, 0x1e, 0x7a, 0x9f, 0x30, 0x91, 0xa9,
	0x34, 0xa8, 0xb9, 0x73, 0xeb, 0xdc, 0xf7, 0x82, 0xbf, 0x80, 0x7d, 0x84, 0x97, 0x9f, 0xa5, 0x2e,
	0x4c, 0x33, 0xc2, 0x2f, 0xa8, 0xa3, 0x0d, 0xd9, 0x1d, 0x5c, 0xaf, 0x50, 0xa8, 0x2c, 0x3a, 0xb6,
	0x75, 0xa8, 0xed, 0x84, 0x7a, 0xbf, 0x1d, 0xb8, 0xdc, 0x84, 0x49, 0x89, 0xec, 0x0e, 0x5c, 0xab,
	0x4e, 0x82, 0xfd, 0x11, 0xf3, 0xad, 0x6f, 0xff, 0x5f, 0x5f, 0x01, 0xd5, 0x99, 0xd7, 0x76, 0x5b,
	0xcb, 0xb7, 0x7f, 0xc0, 0xc0, 0x5d, 0x84, 0x85, 0x21, 0x4d, 0x27, 0xa0, 0xd8, 0xb2, 0xb9, 0x8c,
	0x77, 0xdc, 0xad, 0x98, 0x8d, 0xd9, 0x2b, 0xe8, 0x2c, 0xd4, 0x0f, 0x7e, 0x49, 0xc8, 0x86, 0x96,
	0x3c, 0xca, 0x88, 0x77, 0x2b, 0xf2, 0x28, 0x23, 0x4b, 0xc6, 0xc5, 0x9e, 0x3f, 0xaf, 0xc8, 0xb8,
	0xd8, 0xb3, 0x1b, 0xe8, 0x6e, 0x54, 0x52, 0xa6, 0xc8, 0xaf, 0x08, 0xd6, 0x19, 0x1b, 0xc0, 0xd5,
	0x52, 0x4b, 0x81, 0xe3, 0xf5, 0x9c, 0xf7, 0xa8, 0x72, 0xcc, 0xbd, 0x14, 0xd8, 0xf4, 0xa7, 0xd8,
	0x85, 0x59, 0x8c, 0xb5, 0x53, 0x89, 0x85, 0xfd, 0x4b, 0x43, 0xbf, 0x84, 0x29, 0xd6, 0xcb, 0x6e,
	0x31, 0xf6, 0x00, 0xd7, 0x4d, 0x4e, 0x8b, 0x2a, 0xf8, 0xc5, 0x6d, 0xe7, 0xbe, 0x3f, 0xea, 0x57,
	0x1b, 0x22, 0x16, 0x9c, 0xb4, 0x78, 0x08, 0x6f, 0xa7, 0x59, 0xb8, 0x4d, 0x30, 0x3a, 0xa3, 0x3a,
	0x3f, 0xe7, 0x85, 0x3b, 0xf4, 0x2a, 0xaf, 0x5e, 0xfd, 0xbf, 0x1e, 0x9c, 0x99, 0x19, 0x7d, 0x85,
	0xd7, 0x33, 0x35, 0xa1, 0xa3, 0x5b, 0xd3, 0xd1, 0xad, 0x50, 0x7f, 0x97, 0x02, 0xd9, 0x0c, 0x60,
	0x86, 0x66, 0x2d, 0xc5, 0x1e, 0x75, 0xc1, 0x6e, 0xfc, 0xea, 0xfc, 0xfc, 0xe6, 0xfc, 0xfc, 0xa9,
	0x3d, 0xbf, 0xc1, 0x87, 0x5a, 0xec, 0x29, 0xa7, 0xde, 0xb3, 0x6d, 0x97, 0x46, 0x1e, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x02, 0x95, 0x7c, 0xb5, 0xe0, 0x02, 0x00, 0x00,
}
